#!/usr/bin/env bash
#
# https://docs.docker.com/docker-cloud/builds/advanced/

declare -a tag=$(echo "${DOCKER_TAG}"| \
    sed -r 's|[0-9.]+-wordpress([0-9.]+)-php([0-9.]+)-.+$|("\1" "\2")|g')

php="${tag[1]}"
wordpress="${tag[0]}"

echo '[***] Build hook started'

docker build \
    --build-arg PHP_VERSION="${php}" \
    --build-arg WORDPRESS_VERSION="${wordpress}" \
    -f $DOCKERFILE_PATH \
    -t "${IMAGE_NAME}" .

echo '[***] Build hook ended'
