name: CI
on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/**'
  pull_request:
    branches: [master]
    paths:
      - '**.php'
      - '.github/workflows/**'
  schedule:
    - cron: '32 6 * * 3'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [7.0, latest]
        experimental: [false]
        include:
          - php: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer update --no-interaction --no-scripts
      - name: Run tests
        run: composer run test
